spring.application.name=jwt-nimbus-demo
server.port=8005
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jwt_springboot3?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000
security.jwt.issuer=jwt-nimbus-demo